# Generated by Django 3.1.7 on 2021-03-05 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='card',
            unique_together={('item11', 'item12', 'item13', 'item14', 'item15', 'item21', 'item22', 'item23', 'item24', 'item25', 'item31', 'item32', 'item33', 'item34', 'item35', 'item41', 'item42', 'item43', 'item44', 'item45', 'item51', 'item52', 'item53', 'item54', 'item55')},
        ),
    ]
