# Generated by Django 3.1.7 on 2021-03-05 19:28

from django.db import migrations, models
import game.models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20210305_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='code',
            field=models.CharField(default=game.models.random_code, max_length=6, unique=True),
        ),
    ]
